server:
  port: 50001 
static-path: /home/demo
mybatis:
  type-aliases-package: com.leo.demo.ds.entity
  mapper-locations: classpath:mapper/*.xml
  configuration: 
    mapUnderscoreToCamelCase: true
spring:
  application:
    name: demo
  mvc:
   static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${static-path}
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 15Mb      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.142.106:3307/demoDb?characterEncoding=utf-8&useSSL=false
    username: root
    password: "010407"
    initialSize: 5
    minIdle: 5
    maxIdle: 15
    maxActive: 20
    maxWait: 60000
    
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 间隔多久检测需要关闭的空闲连接 
    timeBetweenEvictionRunsMillis: 60000
    # 池中的连接空闲5分钟后被回收
    minEvictableIdleTimeMillis: 300000
    # 在每次空闲连接回收器线程(如果有)运行时检查的连接数量
    numTestsPerEvictionRun: 10
    # 连接泄漏回收参数
    removeAbandoned: true
    # 连接泄漏回收参数
    removeAbandonedTimeout: 180
    
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50

    filters: stat
    # 超过3秒就是慢，记录
    connectionProperties: druid.stat.slowSqlMillis=3000
    
    